version: "3"
services:
    #PHP Service
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: php:8.1.15-fpm-buster
        container_name: php_word
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/php.ini:/usr/local/etc/php/php.ini
        ports:
            -   "5173:5173"
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: ngnix_word
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
        - "8072:80"
        - "442:443"
